name: release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  on-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
        ref: refs/tags/${{ inputs.tag }}

    - name: fetch notes
      run: git fetch -f --tags origin 'refs/notes/*:refs/notes/*'

    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27

    - name: build
      run: |
        REPO="${{ github.repository }}"
        export RELEASEDL="https://github.com/$REPO/releases/download"
        export PUBLICURL="https://${REPO%/*}.github.io/${REPO#*/}"
        make libs

        make module.prop
        echo "updateJson=$PUBLICURL/update.json" >> module.prop

        make exfatprogs.zip
        sh update.json.sh

        make publish

    - name: release
      uses: softprops/action-gh-release@v3
      with:
        files: exfatprogs.zip
        tag_name: ${{ inputs.tag }}

    - name: push(release-meta)
      uses: actions/upload-pages-artifact@v5
      with:
        name: github-pages
        path: ./public
        retention-days: 1

    - name: deploy(site)
      uses: actions/deploy-pages@v5
# vim: ts=2:et
